version: "3"
services:
  app:
    container_name: nba-stats-server
    build: ./
    depends_on:
      - 'mongo'
    links:
      - mongo
    ports: 
      - "80:80"
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
