export const PlayerStats =
    [{
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 203090,
        PLAYER_NAME: 'Maurice Harkless',
        START_POSITION: 'F',
        COMMENT: '',
        MIN: '12:51',
        FGM: 2,
        FGA: 3,
        FG_PCT: 0.667,
        FG3M: 1,
        FG3A: 1,
        FG3_PCT: 1,
        FTM: 0,
        FTA: 0,
        FT_PCT: 0,
        OREB: 0,
        DREB: 4,
        REB: 4,
        AST: 1,
        STL: 1,
        BLK: 0,
        TO: 0,
        PF: 1,
        PTS: 5,
        PLUS_MINUS: 9
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 202329,
        PLAYER_NAME: 'Al-Farouq Aminu',
        START_POSITION: 'F',
        COMMENT: '',
        MIN: '30:52',
        FGM: 3,
        FGA: 9,
        FG_PCT: 0.333,
        FG3M: 1,
        FG3A: 4,
        FG3_PCT: 0.25,
        FTM: 4,
        FTA: 5,
        FT_PCT: 0.8,
        OREB: 3,
        DREB: 7,
        REB: 10,
        AST: 1,
        STL: 0,
        BLK: 0,
        TO: 0,
        PF: 3,
        PTS: 11,
        PLUS_MINUS: 7
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 202683,
        PLAYER_NAME: 'Enes Kanter',
        START_POSITION: 'C',
        COMMENT: '',
        MIN: '31:40',
        FGM: 5,
        FGA: 10,
        FG_PCT: 0.5,
        FG3M: 0,
        FG3A: 0,
        FG3_PCT: 0,
        FTM: 5,
        FTA: 5,
        FT_PCT: 1,
        OREB: 2,
        DREB: 7,
        REB: 9,
        AST: 1,
        STL: 2,
        BLK: 2,
        TO: 2,
        PF: 3,
        PTS: 15,
        PLUS_MINUS: 6
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 203468,
        PLAYER_NAME: 'CJ McCollum',
        START_POSITION: 'G',
        COMMENT: '',
        MIN: '41:12',
        FGM: 8,
        FGA: 20,
        FG_PCT: 0.4,
        FG3M: 3,
        FG3A: 7,
        FG3_PCT: 0.429,
        FTM: 1,
        FTA: 2,
        FT_PCT: 0.5,
        OREB: 1,
        DREB: 5,
        REB: 6,
        AST: 6,
        STL: 0,
        BLK: 0,
        TO: 3,
        PF: 3,
        PTS: 20,
        PLUS_MINUS: 11
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 203081,
        PLAYER_NAME: 'Damian Lillard',
        START_POSITION: 'G',
        COMMENT: '',
        MIN: '38:36',
        FGM: 5,
        FGA: 17,
        FG_PCT: 0.294,
        FG3M: 1,
        FG3A: 7,
        FG3_PCT: 0.143,
        FTM: 3,
        FTA: 4,
        FT_PCT: 0.75,
        OREB: 0,
        DREB: 4,
        REB: 4,
        AST: 4,
        STL: 2,
        BLK: 1,
        TO: 3,
        PF: 2,
        PTS: 14,
        PLUS_MINUS: 4
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 1628380,
        PLAYER_NAME: 'Zach Collins',
        START_POSITION: '',
        COMMENT: '',
        MIN: '17:00',
        FGM: 5,
        FGA: 6,
        FG_PCT: 0.833,
        FG3M: 0,
        FG3A: 0,
        FG3_PCT: 0,
        FTM: 0,
        FTA: 0,
        FT_PCT: 0,
        OREB: 1,
        DREB: 5,
        REB: 6,
        AST: 1,
        STL: 0,
        BLK: 0,
        TO: 1,
        PF: 5,
        PTS: 10,
        PLUS_MINUS: -2
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 203918,
        PLAYER_NAME: 'Rodney Hood',
        START_POSITION: '',
        COMMENT: '',
        MIN: '27:13',
        FGM: 5,
        FGA: 11,
        FG_PCT: 0.455,
        FG3M: 2,
        FG3A: 6,
        FG3_PCT: 0.333,
        FTM: 3,
        FTA: 4,
        FT_PCT: 0.75,
        OREB: 0,
        DREB: 3,
        REB: 3,
        AST: 0,
        STL: 0,
        BLK: 3,
        TO: 0,
        PF: 0,
        PTS: 15,
        PLUS_MINUS: 4
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 203552,
        PLAYER_NAME: 'Seth Curry',
        START_POSITION: '',
        COMMENT: '',
        MIN: '16:39',
        FGM: 1,
        FGA: 4,
        FG_PCT: 0.25,
        FG3M: 1,
        FG3A: 3,
        FG3_PCT: 0.333,
        FTM: 0,
        FTA: 0,
        FT_PCT: 0,
        OREB: 0,
        DREB: 1,
        REB: 1,
        AST: 1,
        STL: 0,
        BLK: 0,
        TO: 0,
        PF: 1,
        PTS: 3,
        PLUS_MINUS: -4
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 202323,
        PLAYER_NAME: 'Evan Turner',
        START_POSITION: '',
        COMMENT: '',
        MIN: '18:02',
        FGM: 2,
        FGA: 4,
        FG_PCT: 0.5,
        FG3M: 0,
        FG3A: 0,
        FG3_PCT: 0,
        FTM: 0,
        FTA: 0,
        FT_PCT: 0,
        OREB: 0,
        DREB: 4,
        REB: 4,
        AST: 3,
        STL: 0,
        BLK: 0,
        TO: 1,
        PF: 2,
        PTS: 4,
        PLUS_MINUS: 5
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        PLAYER_ID: 1627774,
        PLAYER_NAME: 'Jake Layman',
        START_POSITION: '',
        COMMENT: '',
        MIN: '5:55',
        FGM: 0,
        FGA: 1,
        FG_PCT: 0,
        FG3M: 0,
        FG3A: 1,
        FG3_PCT: 0,
        FTM: 0,
        FTA: 0,
        FT_PCT: 0,
        OREB: 0,
        DREB: 0,
        REB: 0,
        AST: 0,
        STL: 0,
        BLK: 0,
        TO: 0,
        PF: 2,
        PTS: 0,
        PLUS_MINUS: -5
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 1628470,
        PLAYER_NAME: 'Torrey Craig',
        START_POSITION: 'F',
        COMMENT: '',
        MIN: '19:45',
        FGM: 2,
        FGA: 5,
        FG_PCT: 0.4,
        FG3M: 1,
        FG3A: 2,
        FG3_PCT: 0.5,
        FTM: 2,
        FTA: 4,
        FT_PCT: 0.5,
        OREB: 2,
        DREB: 2,
        REB: 4,
        AST: 0,
        STL: 1,
        BLK: 0,
        TO: 0,
        PF: 0,
        PTS: 7,
        PLUS_MINUS: -3
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 200794,
        PLAYER_NAME: 'Paul Millsap',
        START_POSITION: 'F',
        COMMENT: '',
        MIN: '31:39',
        FGM: 6,
        FGA: 14,
        FG_PCT: 0.429,
        FG3M: 1,
        FG3A: 3,
        FG3_PCT: 0.333,
        FTM: 1,
        FTA: 1,
        FT_PCT: 1,
        OREB: 5,
        DREB: 6,
        REB: 11,
        AST: 0,
        STL: 2,
        BLK: 2,
        TO: 2,
        PF: 2,
        PTS: 14,
        PLUS_MINUS: -8
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 203999,
        PLAYER_NAME: 'Nikola Jokic',
        START_POSITION: 'C',
        COMMENT: '',
        MIN: '37:11',
        FGM: 7,
        FGA: 17,
        FG_PCT: 0.412,
        FG3M: 0,
        FG3A: 1,
        FG3_PCT: 0,
        FTM: 2,
        FTA: 4,
        FT_PCT: 0.5,
        OREB: 4,
        DREB: 10,
        REB: 14,
        AST: 7,
        STL: 1,
        BLK: 0,
        TO: 2,
        PF: 5,
        PTS: 16,
        PLUS_MINUS: 2
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 203914,
        PLAYER_NAME: 'Gary Harris',
        START_POSITION: 'G',
        COMMENT: '',
        MIN: '40:28',
        FGM: 4,
        FGA: 12,
        FG_PCT: 0.333,
        FG3M: 0,
        FG3A: 5,
        FG3_PCT: 0,
        FTM: 4,
        FTA: 4,
        FT_PCT: 1,
        OREB: 1,
        DREB: 2,
        REB: 3,
        AST: 2,
        STL: 0,
        BLK: 0,
        TO: 3,
        PF: 4,
        PTS: 12,
        PLUS_MINUS: -8
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 1627750,
        PLAYER_NAME: 'Jamal Murray',
        START_POSITION: 'G',
        COMMENT: '',
        MIN: '35:05',
        FGM: 6,
        FGA: 18,
        FG_PCT: 0.333,
        FG3M: 2,
        FG3A: 8,
        FG3_PCT: 0.25,
        FTM: 1,
        FTA: 1,
        FT_PCT: 1,
        OREB: 3,
        DREB: 4,
        REB: 7,
        AST: 1,
        STL: 1,
        BLK: 0,
        TO: 1,
        PF: 1,
        PTS: 15,
        PLUS_MINUS: -6
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 1627736,
        PLAYER_NAME: 'Malik Beasley',
        START_POSITION: '',
        COMMENT: '',
        MIN: '27:10',
        FGM: 4,
        FGA: 11,
        FG_PCT: 0.364,
        FG3M: 2,
        FG3A: 6,
        FG3_PCT: 0.333,
        FTM: 3,
        FTA: 8,
        FT_PCT: 0.375,
        OREB: 2,
        DREB: 1,
        REB: 3,
        AST: 2,
        STL: 1,
        BLK: 0,
        TO: 0,
        PF: 1,
        PTS: 13,
        PLUS_MINUS: -5
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 1628420,
        PLAYER_NAME: 'Monte Morris',
        START_POSITION: '',
        COMMENT: '',
        MIN: '19:01',
        FGM: 1,
        FGA: 8,
        FG_PCT: 0.125,
        FG3M: 0,
        FG3A: 3,
        FG3_PCT: 0,
        FTM: 1,
        FTA: 2,
        FT_PCT: 0.5,
        OREB: 0,
        DREB: 0,
        REB: 0,
        AST: 6,
        STL: 0,
        BLK: 0,
        TO: 0,
        PF: 3,
        PTS: 3,
        PLUS_MINUS: 3
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 203486,
        PLAYER_NAME: 'Mason Plumlee',
        START_POSITION: '',
        COMMENT: '',
        MIN: '12:12',
        FGM: 3,
        FGA: 7,
        FG_PCT: 0.429,
        FG3M: 0,
        FG3A: 0,
        FG3_PCT: 0,
        FTM: 0,
        FTA: 0,
        FT_PCT: 0,
        OREB: 3,
        DREB: 2,
        REB: 5,
        AST: 1,
        STL: 0,
        BLK: 2,
        TO: 0,
        PF: 3,
        PTS: 6,
        PLUS_MINUS: -8
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        PLAYER_ID: 203115,
        PLAYER_NAME: 'Will Barton',
        START_POSITION: '',
        COMMENT: '',
        MIN: '17:28',
        FGM: 1,
        FGA: 6,
        FG_PCT: 0.167,
        FG3M: 0,
        FG3A: 1,
        FG3_PCT: 0,
        FTM: 2,
        FTA: 2,
        FT_PCT: 1,
        OREB: 3,
        DREB: 8,
        REB: 11,
        AST: 1,
        STL: 0,
        BLK: 1,
        TO: 1,
        PF: 0,
        PTS: 4,
        PLUS_MINUS: -2
    }]

export const TeamStats =
    [{
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_NAME: 'Trail Blazers',
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        MIN: '240:00',
        FGM: 36,
        FGA: 85,
        FG_PCT: 0.424,
        FG3M: 9,
        FG3A: 29,
        FG3_PCT: 0.31,
        FTM: 16,
        FTA: 20,
        FT_PCT: 0.8,
        OREB: 7,
        DREB: 40,
        REB: 47,
        AST: 18,
        STL: 5,
        BLK: 6,
        TO: 10,
        PF: 22,
        PTS: 97,
        PLUS_MINUS: 7
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_NAME: 'Nuggets',
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        MIN: '240:00',
        FGM: 34,
        FGA: 98,
        FG_PCT: 0.347,
        FG3M: 6,
        FG3A: 29,
        FG3_PCT: 0.207,
        FTM: 16,
        FTA: 26,
        FT_PCT: 0.615,
        OREB: 23,
        DREB: 35,
        REB: 58,
        AST: 20,
        STL: 6,
        BLK: 5,
        TO: 9,
        PF: 19,
        PTS: 90,
        PLUS_MINUS: -7
    }]

export const StarterBenchStats =
    [{
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_NAME: 'Trail Blazers',
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        STARTERS_BENCH: 'Starters',
        MIN: '155:11',
        FGM: 23,
        FGA: 59,
        FG_PCT: 0.39,
        FG3M: 6,
        FG3A: 19,
        FG3_PCT: 0.316,
        FTM: 13,
        FTA: 16,
        FT_PCT: 0.813,
        OREB: 6,
        DREB: 27,
        REB: 33,
        AST: 13,
        STL: 5,
        BLK: 3,
        TO: 8,
        PF: 12,
        PTS: 65
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612757,
        TEAM_NAME: 'Trail Blazers',
        TEAM_ABBREVIATION: 'POR',
        TEAM_CITY: 'Portland',
        STARTERS_BENCH: 'Bench',
        MIN: '84:49',
        FGM: 13,
        FGA: 26,
        FG_PCT: 0.5,
        FG3M: 3,
        FG3A: 10,
        FG3_PCT: 0.3,
        FTM: 3,
        FTA: 4,
        FT_PCT: 0.75,
        OREB: 1,
        DREB: 13,
        REB: 14,
        AST: 5,
        STL: 0,
        BLK: 3,
        TO: 2,
        PF: 10,
        PTS: 32
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_NAME: 'Nuggets',
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        STARTERS_BENCH: 'Starters',
        MIN: '164:09',
        FGM: 25,
        FGA: 66,
        FG_PCT: 0.379,
        FG3M: 4,
        FG3A: 19,
        FG3_PCT: 0.211,
        FTM: 10,
        FTA: 14,
        FT_PCT: 0.714,
        OREB: 15,
        DREB: 24,
        REB: 39,
        AST: 10,
        STL: 5,
        BLK: 2,
        TO: 8,
        PF: 12,
        PTS: 64
    },
    {
        GAME_ID: '0041800232',
        TEAM_ID: 1610612743,
        TEAM_NAME: 'Nuggets',
        TEAM_ABBREVIATION: 'DEN',
        TEAM_CITY: 'Denver',
        STARTERS_BENCH: 'Bench',
        MIN: '75:52',
        FGM: 9,
        FGA: 32,
        FG_PCT: 0.281,
        FG3M: 2,
        FG3A: 10,
        FG3_PCT: 0.2,
        FTM: 6,
        FTA: 12,
        FT_PCT: 0.5,
        OREB: 8,
        DREB: 11,
        REB: 19,
        AST: 10,
        STL: 1,
        BLK: 3,
        TO: 1,
        PF: 7,
        PTS: 26
    }]

